### ISSUE TITLE
Замечания по 7.1

### ISSUE THREAD

**Issue by sergey-shambir** [ooccttoobbeerr/lab_7#1]
- у часовой, минутной и секундной стрелок многие параметры выставляются одинаково, меняется лишь sf::Vector2f с размерами стрелок. Следует установку этих параметров вынести в отдельную функцию, общую для трёх стрелок; для рисования каждой стрелки функция вызывается с нужными параметрами.
- следствие предыдущего пункта: из-за копипаста кода код `shapes.secondArrow.setFillColor(Color::White);` встречается дважды, а вот цвет минутной стрелки никем не выставляется.

**Comment by ooccttoobbeerr** [comment]
Исправила

**Comment by sergey-shambir** [comment]
Принято
